package cordismain;

import javax.swing.JLabel;

/**
 *
 * Class that creates a notification window:
 * when flag is true it creates a confirm dialogue.
 * when flag is false it creates an options dialogue.
 *
 * @author dim6ata
 */
public class MessageWindow extends javax.swing.JFrame {

    /**
     * Creates new form MessageWindow
     */
    public MessageWindow(boolean f) {

        returnValue = false;
        flag = f;//when true ok button will be visible; when false the ok+cancel buttons would be visible.
        initComponents();

    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        yellowPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        okButtonPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JLabel();
        okCancelPanel = new javax.swing.JPanel();
        okButton2 = new javax.swing.JLabel();
        cancelButton = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cordis Message");
        setAlwaysOnTop(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 0));

        yellowPanel.setBackground(new java.awt.Color(255, 255, 160));
        yellowPanel.setPreferredSize(new java.awt.Dimension(320, 233));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new javax.swing.OverlayLayout(jPanel2));

        okButtonPanel.setOpaque(false);

        okButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        okButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cordismain/ok-btn-bl.png"))); // NOI18N
        okButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        okButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okButtonMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                okButtonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                okButtonMouseEntered(evt);
            }
        });
        okButton.setVisible(flag);

        javax.swing.GroupLayout okButtonPanelLayout = new javax.swing.GroupLayout(okButtonPanel);
        okButtonPanel.setLayout(okButtonPanelLayout);
        okButtonPanelLayout.setHorizontalGroup(
            okButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, okButtonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        okButtonPanelLayout.setVerticalGroup(
            okButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(okButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(okButtonPanel);

        okCancelPanel.setOpaque(false);

        okButton2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        okButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cordismain/ok-btn-bl.png"))); // NOI18N
        okButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        okButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                okButton2MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                okButton2MouseEntered(evt);
            }
        });

        cancelButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cordismain/cancel-btn-bl.png"))); // NOI18N
        cancelButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelButtonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelButtonMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout okCancelPanelLayout = new javax.swing.GroupLayout(okCancelPanel);
        okCancelPanel.setLayout(okCancelPanelLayout);
        okCancelPanelLayout.setHorizontalGroup(
            okCancelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(okCancelPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(okButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        okCancelPanelLayout.setVerticalGroup(
            okCancelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(okCancelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(okCancelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        okButton2.setVisible(!flag);
        cancelButton.setVisible(!flag);

        jPanel2.add(okCancelPanel);

        jPanel3.setOpaque(false);

        logo.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        logo.setForeground(new java.awt.Color(0, 99, 178));
        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cordismain/design1-smallest.png"))); // NOI18N
        logo.setText("Enter Message Here");
        logo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        logo.setFocusable(false);
        logo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logo.setIconTextGap(45);
        logo.setRequestFocusEnabled(false);
        logo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout yellowPanelLayout = new javax.swing.GroupLayout(yellowPanel);
        yellowPanel.setLayout(yellowPanelLayout);
        yellowPanelLayout.setHorizontalGroup(
            yellowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, yellowPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(yellowPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        yellowPanelLayout.setVerticalGroup(
            yellowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yellowPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(yellowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(yellowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Event handlers:
     * <p>
     */

    private void okButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okButtonMouseEntered

        okButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("ok-btn-w.png")));
    }//GEN-LAST:event_okButtonMouseEntered

    private void okButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okButtonMouseExited

        okButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("ok-btn-bl.png")));
    }//GEN-LAST:event_okButtonMouseExited

    private void okButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okButtonMouseClicked

        this.dispose();

    }//GEN-LAST:event_okButtonMouseClicked

    private void okButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okButton2MouseExited

        okButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("ok-btn-bl.png")));

    }//GEN-LAST:event_okButton2MouseExited

    private void okButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okButton2MouseEntered

        okButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("ok-btn-w.png")));

    }//GEN-LAST:event_okButton2MouseEntered

    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked

        this.dispose();

    }//GEN-LAST:event_cancelButtonMouseClicked

    private void cancelButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseExited

        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("cancel-btn-bl.png")));

    }//GEN-LAST:event_cancelButtonMouseExited

    private void cancelButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseEntered

        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("cancel-btn-w.png")));

    }//GEN-LAST:event_cancelButtonMouseEntered

    /**
     * Getters and setters:
     * <p>
     */
    public JLabel getOkButton2() {

        return okButton2;

    }

    public void setText(String text) {

        logo.setText(text);

    }

    public JLabel getLogo() {

        return logo;

    }

    public boolean isConfirmed() {

        return returnValue;

    }

    public void cancelWindow() {

        this.dispose();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cancelButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel okButton;
    private javax.swing.JLabel okButton2;
    private javax.swing.JPanel okButtonPanel;
    private javax.swing.JPanel okCancelPanel;
    private javax.swing.JPanel yellowPanel;
    // End of variables declaration//GEN-END:variables
    private boolean flag;
    private boolean returnValue;

}
